import React from "react";

/**
 * AuthScreen Component
 * Displays login/register forms (generated by loader)
 */
const AuthScreen: React.FC = () => {
  return null; // HTML is generated by loader
};

export default AuthScreen;
